remote_theme: tareqdandachi/jekyll-shell-theme

title: "https://fpmh.github.io"
tagline: "add me op discord: hmpf#7492"
description: "vooralsnog geen description kunnen bedenken"
github_username: fpmh
#baseurl: "/"
url: "https://fpmh.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: white

header_pages:
  - index.md
  - writeups/index.md
  - technieken/index.md
  - overigen/index.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
