remote_theme: tareqdandachi/jekyll-shell-theme

# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: fpmh's blog
email: hmpf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dit is mijn nieuwe pagina. Deze tekst is enkel geschreven om te kijken wat de description functie doet. Bedankt!
baseurl: "/" # the subpath of your site
url: "fpmh.github.io" # the base hostname & protocol for your site
twitter_username: x86powershell
github_username:  fpmh

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - eerste.md
  - tweede.md
  - derde.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]

menu:
  home: /
  #categories: /categories/
  #about: /about/
  archives: /archives/
  tags: /tags/
  #sitemap: /sitemap.xml
  #commonweal: /404.html
