remote_theme: tareqdandachi/jekyll-shell-theme

title: "hmpf#7492"
tagline: "mijn kennis in ruil voor de jouwe"
description: "geschreven zoals ik het zelf graag zou lezen"
github_username: fpmh
baseurl: "/"
url: "https://fpmh.github.io/"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: white

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
